= About the blog
:hp-tags: blog
:toc: macro
:release: 1.0
:published_at: 2017-01-01
:icons: font

What is this about?

...just another blog where you can find notes from somebody's work programming life.

And that should be it.


What about the motivation for doing that? 

First one is showing that I like what I'm doing and this passion could potentialy help somebody.
The kick off for me to think about starting the blog was
https://vimeo.com/99516367[presentation Jurgen Appelo at GeeCon 2014]. I've watched several
other presentations from Jurgen before and after but this particularly hit me. 

The second is my infinite fight with recording knowledge. I usualy read something and
I forget what that thing was about after few weeks. All simply goes to  the `/dev/null` black hole.
I found out that putting down notes helping me to summarize the key message while
helping me to remember at least some part of the topic.
And it's kind of time machine for me being able to get back in time
to understand what I was thinking some time before icon:smile-o[].

