= Links
:hp-tags: blog
:toc: macro
:release: 1.0
:published_at: 2017-05-05
:icons: font

List of links that seems to me being somehow interesting

== Java

https://www.ibm.com/developerworks/library/j-nativememory-linux[Thanks for the memory, Linux]::
awsome article about Java memory management in Linux and mainly on topic of native memory issues.
There is another article talking about this topic
https://www.ibm.com/developerworks/java/library/j-nativememory-aix/[on AIX too].

== Transactions

https://www.youtube.com/watch?v=5ZjhNTM8XU8[Transactions: myths, surprises and opportunities]::
presentation by Martin Kleppmann for Strange Loop 2015. He summarizes what is transaction, what ACID means, how disstributed world changed the perception.

https://www.infoq.com/minibooks/JTDS[Java Transaction Design Strategies, ebook]::
perfect introduction to transaction in Java. You will learn what is local
transaction, global transaction, two-phase commit, what you can expect from JTA and most of the examples are for Java EE and Spring too.

https://www.microsoft.com/en-us/research/publication/replicated-data-consistency-explained-through-baseball/[Replicated Data Consistency Explained Through Baseball]::
eventual consistency explained on the example of the baseball game. I find it really comprehensible and nicely written.


