= Links
:hp-tags: blog
:toc: macro
:release: 1.0
:published_at: 2017-05-05
:icons: font

List of links I found interesting

== Transactions

https://www.youtube.com/watch?v=5ZjhNTM8XU8[Transactions: myths, surprises and opportunities]::
presentation by Martin Kleppmann for Strange Loop 2015. He summarizes what is transaction, what ACID means, how disstributed world changed the perception.

https://www.infoq.com/minibooks/JTDS[Java Transaction Design Strategies, ebook]::
perfect introduction to transaction in Java. You will learn what is local
transaction, global transaction, two-phase commit, what you can expect from JTA and most of the examples are for Java EE and Spring too.

https://www.microsoft.com/en-us/research/publication/replicated-data-consistency-explained-through-baseball/[Replicated Data Consistency Explained Through Baseball]::
eventual consistency explained on the example of the baseball game. I find it really comprehensible and nicely written.

https://engineering.linkedin.com/distributed-systems/log-what-every-software-engineer-should-know-about-real-time-datas-unifying[The Log: What every software engineer should know about real-time data's unifying abstraction]::
I find this (quite long) article perfect summary of what the event sourcing is about. This is look from stream processing side "point of view" but all that gives much sense. How the stream processing and event source differs or what they are in common is nicely taken by presentation by Martin Klepmann at https://www.youtube.com/watch?v=avi-TZI9t2I

== Design

https://www.youtube.com/watch?v=STKCRSUsyP0[The Many Meanings of Event-Driven Architecture]::
nice summary of meening of terms that you hit when reading about event-driven design. I like how the presentation was informative but comperehensible.

== Java

https://www.ibm.com/developerworks/library/j-nativememory-linux[Thanks for the memory, Linux]::
awsome article about Java memory management in Linux and mainly on topic of native memory issues.
There is another article talking about this topic
https://www.ibm.com/developerworks/java/library/j-nativememory-aix/[on AIX too].



