= About the blog
:hp-tags: blog
:toc: macro
:release: 1.0
:published_at: 2017-01-01
:icons: font

What is this about?

...just another blog where you can find notes from somebody's work programming life.

And that should be it.


There is still a motivation for doing that, sure. Few reasons, solely selfish.

First one is showing that I like what I'm doing and this passion could potentialy help somebody.
The kick of for me thinking about such thing was
https://vimeo.com/99516367[presentation Jurgen Appelo at GeeCon 2014]. I watched several
other presentations from Jurgen afterwards but this one somehow influenced my thinking.

The second is my infinite fight with recording knowledge. I usualy read something and
I forget what that thing was about after few weeks. If not used in short period of time then
it goes to `/dev/null` black hole.
I found out that putting down few notes summarized in my own words helps me
in this endeavour. Plus it works as kind of time machine to get back in time
to understand what I was thinking to understand icon:smile-o[].

Yeap, the only trouble is that writing such notes take a good amount of time.
But mostly it's worthy.

Then writing in English to enhance my skills. +
Hmm... I still hope that it could be readable.
